# config.toml
IP = "localhost:5432"
DBName = "postgres"
Login = "test"
Password = "test"
Sslmode = "disable"

[[tables]]
  TableName = "hour_params"
[[tables]]
  TableName = "hour_params_test1"
[[tables]]
  TableName = "min_params"